name: Build and Release Rust Project

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build Rust Project
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install Protobuf Compiler
      run: choco install protoc

    - name: Build Release
      run: cargo build --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: rust-release-binary
        path: target/release/beat-saber-maps-scraper.exe

  publish:
    name: Publish Release
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: rust-release-binary

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./rust-release-binary/beat-saber-maps-scraper.exe"
        draft: true
